### ISSUE TITLE
failed, when npm run build:local

### ISSUE THREAD

**Issue by ypenghui6** [lucusfly/iost-extension#4]
PS D:\yanpeng\GOPath\src\github.com\lucusfly\iost-extension> npm run build:local

> toshi-frontend-boilerplate@0.0.1 build:local D:\yanpeng\GOPath\src\github.com\lucusfly\iost-extension
> NODE_ENV=local webpack --config webpack.prod.config.js && gulp build

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! toshi-frontend-boilerplate@0.0.1 build:local: `NODE_ENV=local webpack --config webpack.prod.config.js && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the toshi-frontend-boilerplate@0.0.1 build:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yanpeng\AppData\Roaming\npm-cache\_logs\2019-03-21T06_34_40_612Z-debug.log

**Comment by aresastro** [comment]
This is a windows build error. You have to change NODE_ENV=local to set NODE_ENV=local. You may also need to try using Yarn.
